<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pulang-pergi_Toggle_knob__srezn Toggle__552cbe</name>
   <tag></tag>
   <elementGuidId>3a2f6788-80c0-4abc-a5a8-d5ebe74de2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div/div[2]/div[2]/div/label/div/label/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Toggle_knob__srezn.Toggle_knob_large__2BQdH</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c643790c-9e03-49bb-8ae9-b508a4a1ac7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toggle_knob__srezn Toggle_knob_large__2BQdH</value>
      <webElementGuid>669a097e-6223-4dc9-b1b5-7b12bb2e5d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;AppLayout_main__GlPPb&quot;]/div[@class=&quot;flight_wrapper__00uBz&quot;]/div[@class=&quot;Hero_wrapper__Li4qE Hero_overlay__I5Sz9&quot;]/div[@class=&quot;Hero_container__0xNr_&quot;]/div[@class=&quot;SearchForm_search_form__0e7Al SearchForm_desktop_landing__iBYki&quot;]/div[@class=&quot;SearchForm_date_picker__cYUsk SearchForm_desktop__SBAm7&quot;]/div[@class=&quot;SearchForm_date_input__xPYSQ SearchForm_date_flex__yHqn9&quot;]/label[@class=&quot;SearchForm_round_trip__x_McQ&quot;]/div[@class=&quot;Toggle_container__bqLHX&quot;]/label[1]/div[@class=&quot;Toggle_toggle__naszi Toggle_toggle_large__JPqw0&quot;]/div[@class=&quot;Toggle_knob__srezn Toggle_knob_large__2BQdH&quot;]</value>
      <webElementGuid>db80c1d8-3dea-48c0-bef1-96d7a6fcf392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div/div[2]/div[2]/div/label/div/label/div/div</value>
      <webElementGuid>b907917d-bc09-458c-89d2-09125f960a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div</value>
      <webElementGuid>0c109788-2a3e-4c90-924c-9a42704bdef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
