<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1dfb78a8-9a14-424a-b5f4-d34af2eceba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/header/div/div[3]/div[2]/div/div[2]/div/ul/li/a/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Tiket Pesawat&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b230a88d-c935-4357-9448-b41f5b28ec93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Tiket Pesawat</value>
      <webElementGuid>c15ae103-346e-4e19-b670-8a22796a9f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit9696gsm/vertical/2024/04/16/e1649ab6-a99a-4990-a65d-038cd6058b91-1713201694934-5add791aac1d0a16bbd30b2792f85e96.png</value>
      <webElementGuid>f29c4c59-223b-4c5e-b7f0-4aa6f95c4286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8ea49eff-bead-4bc2-b76f-8072a894f803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>cc37921c-cb1a-467a-bc19-24c59a914be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;index_main___rT19&quot;]/header[@class=&quot;index_header__25ySr&quot;]/div[@class=&quot;index_header_inner__ZgIbg&quot;]/div[@class=&quot;index_content__k_CP2 index_desktop_only__ss43k&quot;]/div[2]/div[@class=&quot;VerticalIcons_list__SWa9c&quot;]/div[@class=&quot;VerticalIcons_listIcon__rGlIP&quot;]/div[@class=&quot;VerticalIcons_wrapper__4jHIR&quot;]/ul[1]/li[1]/a[1]/div[@class=&quot;VerticalIcons_icon__M26iM&quot;]/span[1]/img[1]</value>
      <webElementGuid>91d6fc20-6a55-4fd5-9fcd-b6bb5d9dc29e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/header/div/div[3]/div[2]/div/div[2]/div/ul/li/a/div/span/img</value>
      <webElementGuid>ba99da6a-5987-4992-bab0-fd2b367916fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Tiket Pesawat']</value>
      <webElementGuid>124f9cfc-90dc-4e62-a953-4105584ea458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span/img</value>
      <webElementGuid>143529bc-b635-47b1-998d-786c47a48e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Tiket Pesawat' and @src = 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/rsfit9696gsm/vertical/2024/04/16/e1649ab6-a99a-4990-a65d-038cd6058b91-1713201694934-5add791aac1d0a16bbd30b2792f85e96.png']</value>
      <webElementGuid>f1765cd8-b9ab-4dec-b55c-6449c57e5178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
